# Generated by Django 3.1 on 2020-12-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioimagecatergories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioImageCatergories',
            new_name='PortfolioImageCategorie',
        ),
    ]
