# Generated by Django 3.1 on 2020-12-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201231_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimagecategorie',
            options={'verbose_name_plural': 'PluralForMyModel'},
        ),
    ]
