# Generated by Django 3.1 on 2020-12-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20201231_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioimagecategories',
            old_name='title',
            new_name='category',
        ),
    ]
