# Generated by Django 3.1 on 2020-12-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201231_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioImageCategories',
            new_name='ImageCategory',
        ),
        migrations.AlterModelOptions(
            name='imagecategory',
            options={'verbose_name_plural': 'Image Category'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'verbose_name_plural': 'Portfolio Image'},
        ),
    ]
