# Generated by Django 3.1 on 2020-12-31 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201231_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='category',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
