# Generated by Django 3.1 on 2021-01-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portfolioimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchbookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='sketchbookimages/')),
            ],
            options={
                'verbose_name_plural': 'Sketchbook Image',
            },
        ),
    ]
