# Generated by Django 3.1 on 2021-01-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_sketchbookimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Typer',
            },
        ),
    ]
